config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => "my_registrations"
    }, :path => 'auth', :path_names => {
    :sign_in => 'login', :sign_out => 'logout'
  }
  resources :users do
    member do
      get 'send_profile_card'
    end
  end


  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get "/about", to: 'users#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :photo, PhotoUploader

  validates :first_name, :last_name, :presence => true, :length => {:minimum => 2}

  def full_name
    "#{first_name} #{last_name}"
  end

  # pagination size
  self.per_page = 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :store_current_location, :unless => :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :photo, :profile, :email, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  private
  # override the devise helper to store the current location so we can
  # redirect to it after loggin in or out. This override makes signing in
  # and signing up work automatically.
  def store_current_location
    store_location_for(:user, request.url)
  end
end

app/controllers/my_registrations_controller.rb
class MyRegistrationsController < Devise::RegistrationsController

  def create
    begin
      raise "error" if rand(3) > 1
    rescue
      render(file: "#{Rails.root}/public/500.html", 
        layout: false, status: 500) and return
    end
    super
    if @user.persisted?
      begin
        UserMailer.new_registration(@user).deliver!
        flash[:notice] = "You have successfully signed up on the website. Login and password were sent to your mail."
      rescue
        flash[:notice] = "You have successfully signed up on the website."
      end
    end
  end

  def error
    render :html => "<strong>500</strong><p>Internet Servise Error</p>".html_safe and return
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :send_profile_card]

  def about
    render html: "<strong>About</strong><p></p>".html_safe
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if current_user != @user
      redirect_to users_path
    end
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if current_user != @user
      redirect_to users_path
    end

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_profile_card
    begin
      UserMailer.user_card_mail(@user, current_user.email).deliver!
      flash[:notice] = "User cart has been sent to your email"
    rescue
      flash[:alert] = "Mailer error. Contact administrator"
    end

    begin
      redirect_to :back
    rescue ActionController::RedirectBackError
      redirect_to user_path @user
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :photo, :profile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_sign_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.erb
<h1>Header</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestersApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="content">
      <%= render 'shared/header' %>
      <%= render 'shared/navigation' %>
      <div id="main">
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_footer.erb
<div id="footer">
	<div>Copyright ©2016 all rights reserved </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
	<div>Copyright ©2016 all rights reserved </div>
</div>

app/views/shared/_header.erb
<div class="page-header">
  <h1>Tester's app<small></small></h1>
</div>

app/views/shared/_header.html.erb
<div class="page-header">
  <%= image_tag 'light_it_logo', :id => 'logo' %>
  <h1>Tester's app</h1>
</div>

app/views/shared/_navigation.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li  class="<%= 'active' if current_page?(user_path(current_user)) || 
          current_page?(edit_user_path(current_user)) %>"><%=link_to "My account", user_path(current_user) %></li>
          <li  class="<%= 'active' if !current_page?(user_path(current_user)) &&
          !current_page?(edit_user_path(current_user)) %>"><a href="/users">Users</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li ><span class="navbar-text">Здравствуйте, 
            <% if current_user.first_name != ''  && current_user.last_name != '' %>
              <%= current_user.last_name %> <%= current_user.first_name.to_s.first %>.
            <% elsif current_user.first_name != '' %>
              <%= current_user.first_name %>
            <% elsif current_user.last_name != '' %>
              <%= current_user.last_name %>
            <% else %>
              <%= current_user.email %>
            <% end %>
          </span></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li  class="<%= 'active' if current_page?(controller: 'devise/sessions', action: 'new') %>"><%= link_to 'Sing in', new_user_session_path %></li>
          <li  class="<%= 'active' if current_page?(controller: 'devise/registrations', action: 'new') %>"><%= link_to 'Sing up', new_user_registration_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li  class="<%= 'active' if current_page?(user_path(current_user)) ||
              current_page?(edit_user_path(current_user)) %>">
            <%=link_to "My account", user_path(current_user) %>
          </li>
          <li  class="<%= 'active' if !current_page?(user_path(current_user)) &&
              !current_page?(edit_user_path(current_user)) %>">
            <a href="/users">Users</a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">Learn more
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/about">About this site</a></li>
              <li><a href="http://light-it.net/ru/">About company</a></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li ><span class="navbar-text">Здравствуйте,
            <% if current_user.first_name != ''  && current_user.last_name != '' %>
              <%= current_user.last_name %> <%= current_user.first_name.to_s.first %>.
            <% elsif current_user.first_name != '' %>
              <%= current_user.first_name %>
            <% elsif current_user.last_name != '' %>
              <%= current_user.last_name %>
            <% else %>
              <%= current_user.email %>
            <% end %>
          </span></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li  class="<%= 'active' if current_page?(controller: 'devise/sessions', action: 'new') %>"><%= link_to 'Sing in', new_user_session_path %></li>
          <li  class="<%= 'active' if current_page?(controller: '/my_registrations', action: 'new') %>">
            <%= link_to 'Sing up', new_user_registration_path %>
          </li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/_form.html.erb
<%= form_for(user, :html => {:class => "form-horizontal edit_form"}) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => 'form-control',
      :data => {:validation => "required email_check"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :first_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
  </div>

<!--   <div class="form-group">
    <div class="col-sm-10">
      <%= image_tag @user.photo%>
    </div>
  </div> -->

  <div class="form-group">
    <%= f.label :photo, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= image_tag @user.photo%>
      <%= f.file_field :photo, :data => {:validation => "size file_chek", 
        :validation_allowing =>"jpg, png, gif",
        :validation_max_size => "1024kb" } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :profile, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :profile, :class => 'form-control',
      :data => {:validation => 'length', :validation_length => 'max200'} %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, :class => "btn btn-default" %> |
<%= link_to 'Back', users_path, :class => "btn btn-default" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= will_paginate @users, renderer: BootstrapPagination::Rails%>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Email</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Photo</th>
        <th>Profile</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= image_tag user.photo, :class => "img-thumbnail" %></td>
          <td><%= link_to 'Show', user, :class => 'btn btn-default' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate @users, renderer: BootstrapPagination::Rails%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, :class => 'btn btn-default' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<h1>User info</h1>
<div class="row">
  <div class="col-sm-2"><strong>Email:</strong></div>
  <div class="col-sm-2"><%= @user.email %></div>
</div>
<div class="row">
  <div class="col-sm-2"><strong>First name:</strong></div>
  <div class="col-sm-2"><%= @user.first_name %></div>
</div>
<div class="row">
  <div class="col-sm-2"><strong>Last name:</strong></div>
  <div class="col-sm-2"><%= @user.last_name %></div>
</div>
<div class="row">
  <div class="col-sm-2"><strong>Photo:</strong></div>
  <div class="col-sm-2"><%= image_tag @user.photo, :class => "img-thumbnail" %></div>
</div>
<div class="row">
  <div class="col-sm-2"><strong><strong>Profile:</strong></strong></div>
  <div class="col-sm-2"><%= @user.profile %></div>
</div>

<%= link_to 'Send profile card to email', send_profile_card_user_path(@user),
  :class => "btn btn-default"%>
<%= link_to 'Edit', edit_user_path(@user), :class => "btn btn-default" %> |
<%= link_to 'Back', users_path, :class => "btn btn-default" %>